# Generated by Django 3.0.2 on 2020-03-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filmy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('rok', models.IntegerField()),
                ('url', models.CharField(max_length=100)),
                ('hodnoceni', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Idecka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tvurce', models.CharField(max_length=100)),
                ('id_filmu', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tvurci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100)),
                ('id_tvurce', models.CharField(max_length=100)),
            ],
        ),
    ]
